shell: bash --noprofile --norc -e -o pipefail {0}
TEST_OUTPUT_DIR=/__w/django-rest-api/django-rest-api/test_reports/
2022-08-18 06:15:41,015                             none INFO core.adapters.file_conversion.auto_fallback_conversion_adapter AutoFallbackFileConversionAdapter created with 2 converters
2022-08-18 06:15:42,916                             none INFO core.apps    Setting the file conversion adapter to Onlyoffice Converter.
2022-08-18 06:15:42,916                             none INFO core.apps    Setting the elastic search connection to a dummy instance.
2022-08-18 06:15:42,916                             none WARN core.apps    GOOGLE_MAPS_GEOCODING_APIKEY missing, Using DummyGeocodeClientAdapter
2022-08-18 06:15:42,916                             none INFO core.apps    Creating the auto fallback pdf merge adapter/
2022-08-18 06:15:43,549                             none ERRO ddtrace.internal.writer failed to send traces to Datadog Agent at http://localhost:8126
..............2022-08-18 06:28:47,467                             none INFO tray_integrations.tray_solution_instance.domain.use_cases.update_tray_solution_instance tray workflow, proxy <Mock name='mock.execute().id' id='140193477558160'> created for instance id TYmAhqBWJZTndoDWrmjH
2022-08-18 06:28:47,467                             none INFO tray_integrations.tray_solution_instance.domain.use_cases.update_tray_solution_instance tray workflow, proxy <Mock name='mock.execute().id' id='140193477558160'> created for instance id TYmAhqBWJZTndoDWrmjH
.2022-08-18 06:28:47,471                             none ERRO tray_integrations.tray_solution_instance.domain.use_cases.update_tray_solution_instance No workflow found with tray workflow id 248a1628-45d2-4182-b33c-6ed1d7f5a67d and instance id nwinwroigiogrwgbowgi
.......2022-08-18 06:28:47,524                             none ERRO tray_integrations.tray_workflow_proxy.domain.use_cases.send_proxy_request_use_case Call to tray webhook url failed: 
...
======================================================================
FAIL [0.286s]: test_post_external_api_create_counter_party (public.counter_party.tests.test_counter_party_api_views_v2_1.TestCounterpartyCreateView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/public/counter_party/tests/test_counter_party_api_views_v2_1.py", line 60, in test_post_external_api_create_counter_party
    self.assertEqual(address_created.country.code2, self.country.code2)
AssertionError: 'SC' != 'BH'
- SC
+ BH


----------------------------------------------------------------------


FAIL [0.013s]: test_get_tags_for_entity (core.entity_tag_mapping.tests.data.test_db_repo.EntityTagMappingDbRepositoryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/core/entity_tag_mapping/tests/data/test_db_repo.py", line 38, in test_get_tags_for_entity
    self.assertEqual(result, [EntityTagMappingDomainModel.from_orm(mapping1)])
AssertionError: Lists differ: [Enti[177 chars]t'>)), EntityTagMappingDomainModel(entity_id=6[143 chars]'>))] != [Enti[177 chars]t'>))]

First list contains 1 additional elements.
First extra element 1:
EntityTagMappingDomainModel(entity_id=6819, tag=TagsResponse(id=35, name='test_contract_tag', workspace_id=561, colour_code='test', tag_entity_type=<TagEntityType.CONTRACT: 'Contract'>))

Diff is 957 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL [0.288s]: test_post_questionnaire_data (sd_admin.questionnaire.tests.presentation.test_views.TestTemplateQuestionnaireMigrationView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/dependency_injector/wiring.py", line 612, in _patched
    result = fn(*args, **to_inject)
  File "/app/sd_admin/questionnaire/tests/presentation/test_views.py", line 280, in test_post_questionnaire_data
    self.assertEqual(template_role_db, template_role_details)
AssertionError: Contr[116 chars]r_id=795, label='UkrxigfjfLSdyOCKsYjp', is_cre[84 chars]on'>) != Contr[116 chars]r_id=None, label='DFntxNorIWPzwVvZXcae', is_cr[85 chars]on'>)

Ran 4114 tests in 744.719s

FAILED (failures=3)

Generating XML reports...
Preserving test database for alias 'default'...
Wrote LCOV report to /__w/django-rest-api/django-rest-api/test_reports/coverage.lcov
Error: Process completed with exit code 1.


Expected output:

FAIL [0.288s]: function ()
-------------------------------------
Traceback (most recent call last):
  File 
  File 
AssertionError: 

FAILED (failures=1)

